name: release

on:
  push:
    branches:
      - main


permissions:
  contents: write # Required for release-please
  issues: write # Required for release-please
  pull-requests: write # Required for release-please
  id-token: write # Required for npm publishing

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@5c625bfb5d1ff62eadeeb3772007f7f66fdcf071 # v4.4.1
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        if: ${{ steps.release.outputs.release_created }}
      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'
        if: ${{ steps.release.outputs.release_created }}
      - run: pnpm install --frozen-lockfile
        if: ${{ steps.release.outputs.release_created }}
      - run: pnpm test
        if: ${{ steps.release.outputs.release_created }}
      - run: pnpm publish
        if: ${{ steps.release.outputs.release_created }}
